export const SITE_TITLE = "Elvinlab";
export const SITE_DESCRIPTION = "Welcome to my website!";
export const EMAIL = "elvinlab@outlook.com";
export const AVATAR_LINK = "/imgs/UI/profile.webp";
export const LINKEDIN_LINK = "https://www.linkedin.com/in/elvinlab/";
export const CURRENT_COMPANY = "https://www.linkedin.com/company/getbuo/";
export const RESUME_ES_LINK =
  "https://drive.google.com/file/d/1W1e7tGAeaOTp80ke3I9-5hUbUGfEiE84/view?usp=drive_link";
export const RESUME_EN_LINK =
  "https://drive.google.com/file/d/1Y9Qmr5sk4iTJIRB-IXkdE9E-V3yRa5aO/view?usp=drive_link";
export const GITHUB_LINK = "https://github.com/elvinlab";
